mineral_catalog/mineral_catalog/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('', include(('minerals.urls', 'minerals'),
                               namespace='minerals')),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

mineral_catalog/minerals/urls.py
from django.urls import path

from minerals import views


urlpatterns = [
    path('', views.mineral_list, name='list'),
    path('<int:pk>/', views.mineral_detail, name='detail'),
]

mineral_catalog/minerals/models.py
from django.db import models


class Mineral(models.Model):
    name = models.CharField(max_length=255, blank=True, default='')
    image_filename = models.CharField(max_length=255, blank=True, default='')
    image_caption = models.CharField(max_length=255, blank=True, default='')
    category = models.CharField(max_length=255, blank=True, default='')
    formula = models.CharField(max_length=255, blank=True, default='')
    strunz_classification = models.CharField(max_length=255, blank=True,
                                             default='')
    color = models.CharField(max_length=255, blank=True, default='')
    crystal_system = models.CharField(max_length=255, blank=True,
                                      default='')
    unit_cell = models.CharField(max_length=255, blank=True, default='')
    crystal_symmetry = models.CharField(max_length=255, blank=True,
                                        default='')
    cleavage = models.CharField(max_length=255, blank=True, default='')
    mohs_scale_hardness = models.CharField(max_length=255, blank=True,
                                           default='')
    luster = models.CharField(max_length=255, blank=True, default='')
    streak = models.CharField(max_length=255, blank=True, default='')
    diaphaneity = models.CharField(max_length=255, blank=True, default='')
    optical_properties = models.CharField(max_length=255, blank=True,
                                          default='')
    refractive_index = models.CharField(max_length=255, blank=True, default='')
    crystal_habit = models.CharField(max_length=255, blank=True, default='')
    specific_gravity = models.CharField(max_length=255, blank=True, default='')
    group = models.CharField(max_length=255, blank=True, default='')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.name

mineral_catalog/minerals/views.py
from django.shortcuts import render, get_object_or_404
from django.db import IntegrityError
from django.forms.models import model_to_dict
import random
import json

from .models import Mineral


MINERALS = Mineral.objects.all()


def mineral_dict(mineral):
    '''This function composes data entries from minerals.json into individual
    dicts which then are passed into the add_mineral function to and is
    added to the database.'''
    fields = {
        'name': 'N/a',
        'image_filename': 'N/a',
        'image_caption': 'N/a',
        'category': 'N/a',
        'formula': 'N/a',
        'strunz_classification': 'N/a',
        'crystal_system': 'N/a',
        'unit_cell': 'N/a',
        'color': 'N/a',
        'crystal_symmetry': 'N/a',
        'cleavage': 'N/a',
        'mohs_scale_hardness': 'N/a',
        'luster': 'N/a',
        'streak': 'N/a',
        'diaphaneity': 'N/a',
        'optical_properties': 'N/a',
        'refractive_index': 'N/a',
        'crystal_habit': 'N/a',
        'specific_gravity': 'N/a',
        'group': 'N/a'
    }
    for field, value in mineral.items():
        fields[field] = value
    return fields


def add_minerals():
    '''This function adds json entries into the database.'''
    with open('minerals.json', encoding='utf-8') as file:
        minerals = json.load(file)
        for mineral in minerals:
            try:
                fields = mineral_dict(mineral)
                Mineral(
                    name=fields['name'],
                    image_filename=fields['image_filename'],
                    image_caption=fields['image_caption'],
                    category=fields['category'],
                    formula=fields['formula'],
                    strunz_classification=fields['strunz_classification'],
                    crystal_system=fields['crystal_system'],
                    unit_cell=fields['unit_cell'],
                    color=fields['color'],
                    crystal_symmetry=fields['crystal_symmetry'],
                    cleavage=fields['cleavage'],
                    mohs_scale_hardness=fields['mohs_scale_hardness'],
                    luster=fields['luster'],
                    streak=fields['streak'],
                    diaphaneity=fields['diaphaneity'],
                    optical_properties=fields['optical_properties'],
                    refractive_index=fields['refractive_index'],
                    crystal_habit=fields['crystal_habit'],
                    specific_gravity=fields['specific_gravity'],
                    group=fields['group']
                ).save()
            except IntegrityError:
                continue


def random_pk():
    pk = random.choice(MINERALS).id
    return Mineral.objects.get(pk=pk)


def mineral_list(request):
    # add_minerals()
    return render(request, 'minerals/mineral_list.html',
                  {
                      'minerals': MINERALS,
                      'random_mineral': random_pk(),
                      })


def mineral_detail(request, pk):
    mineral = model_to_dict(get_object_or_404(Mineral, pk=pk))
    return render(request, 'minerals/mineral_detail.html',
                  {
                      'mineral': mineral,
                      'random_mineral': random_pk(),
                      })

mineral_catalog/minerals/templates/minerals/layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Macky's Minerals: A magnificant catalog of minerals</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
  <div class="bounds">
    <div class="grid-100">
      <a href="{% url 'minerals:list' %}">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Macky's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>
        {% block content %}{% endblock %}
  </div>  
  <div class="minerals__random">
    <a class="minerals__anchor" href="{% url 'minerals:detail' pk=random_mineral.pk %}">Show random mineral</a>
  </div>
</body>
</html>

mineral_catalog/minerals/templates/minerals/mineral_detail.html
{% extends "minerals/layout.html" %}
{% load mineral_extras %}
{% load static %}

{% block content %}
<div class="grid-100 mineral__container">
    <h1 class="mineral__name">{{ mineral.name }}</h1>
    <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static 'images' %}/{{ mineral.image_filename }}">
        <p class="mineral__caption">{{ mineral.image_caption }}</p>
    </div>
    <div class="mineral__table-container">
        <table class="mineral__table">
            {% for field, value in mineral.items %}
                {% if field == "category" or field == "formula" or field == "color" or field == "crystal_system" %}
                    <tr>
                        <td class="mineral__category">{{ field|title|reverse_snake }}</td>
                        <td>{{ value }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>
    ---
    <div class="mineral__table-container">
        <table class="mineral__subtable">
            {% for field, value in mineral.items %}
                {% if field != "name" and field != "id" and field != "image_filename" and field != "image_caption" and field != "category" and field != "formula" and field != "color" and field != "crystal_system" %}
                    <tr>
                        <td class="mineral__subcategory">{{ field|title|reverse_snake }}</td>
                        <td>{{ value }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

mineral_catalog/minerals/templates/minerals/mineral_list.html
{% extends 'minerals/layout.html' %}

{% block content %}
<h1>Mineral List</h1>

<div class="grid-100">
    <ul class="minerals__container">
    {% for mineral in minerals %}
      <li class="minerals__item">
        <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name }}</a>
      </li>
    {% endfor %}
    </ul>
  </div>

{% endblock %}